import { Product, FilterCategory } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Chêne Avivé - Qualité QF1a',
    image: 'https://picsum.photos/seed/wood1/400/300',
    essence: 'oak',
    type: 'edged',
    quality: 'QF1a (Premium)',
    drying: 'Sec séchoir (KD)',
    thickness: '27mm',
    lengths: 'Panachées 2m-3m',
    seller: 'Scierie du Centre',
    stock: 50,
    pricePerM3: 950,
    currency: '€',
  },
  {
    id: '2',
    title: 'Chêne Avivé - Qualité QF2',
    image: 'https://picsum.photos/seed/wood2/400/300',
    essence: 'oak',
    type: 'edged',
    quality: 'QF2 (Standard)',
    drying: 'Ressuyé',
    thickness: '34mm',
    lengths: 'Fixes 2.50m',
    seller: 'Bois & Forêts Est',
    stock: 120,
    pricePerM3: 780,
    currency: '€',
  },
  {
    id: '3',
    title: 'Chêne Plots - Qualité QF1b',
    image: 'https://picsum.photos/seed/wood3/400/300',
    essence: 'oak',
    type: 'boules',
    quality: 'QF1b',
    drying: 'Sec air (AD)',
    thickness: '54mm',
    lengths: '3m+',
    seller: 'Scierie du Centre',
    stock: 15,
    pricePerM3: 1100,
    currency: '€',
  },
  {
    id: '4',
    title: 'Chêne Avivé Large - Qualité QF1a',
    image: 'https://picsum.photos/seed/wood4/400/300',
    essence: 'oak',
    type: 'edged',
    quality: 'QF1a',
    drying: 'Sec séchoir (KD)',
    thickness: '27mm',
    lengths: 'Panachées 2.5m-3.5m',
    seller: 'Groupe Bois France',
    stock: 35,
    pricePerM3: 990,
    currency: '€',
  },
  {
    id: '5',
    title: 'Chêne Frises - Qualité QF3',
    image: 'https://picsum.photos/seed/wood5/400/300',
    essence: 'oak',
    type: 'edged',
    quality: 'QF3 (Rustique)',
    drying: 'Sec séchoir (KD)',
    thickness: '27mm',
    lengths: 'Courtes 1m-1.5m',
    seller: 'Scierie Alpine',
    stock: 200,
    pricePerM3: 550,
    currency: '€',
  },
  {
    id: '6',
    title: 'Chêne Poutres - Structurel',
    image: 'https://picsum.photos/seed/wood6/400/300',
    essence: 'oak',
    type: 'beams',
    quality: 'Charpente',
    drying: 'Frais de sciage',
    thickness: '200x200mm',
    lengths: 'Sur mesure',
    seller: 'Bois & Forêts Est',
    stock: 80,
    pricePerM3: 620,
    currency: '€',
  },
];

export const FILTERS: FilterCategory[] = [
  {
    id: 'essence',
    title: 'Essence',
    options: [
      { id: 'oak', label: 'Chêne', count: 42, checked: true },
      { id: 'beech', label: 'Hêtre', count: 15 },
      { id: 'pine', label: 'Pin', count: 86 },
      { id: 'spruce', label: 'Épicéa', count: 34 },
    ],
  },
  {
    id: 'type',
    title: 'Type de produit',
    options: [
      { id: 'edged', label: 'Avivés', count: 24 },
      { id: 'boules', label: 'Plots', count: 12 },
      { id: 'beams', label: 'Poutres', count: 5 },
      { id: 'panels', label: 'Panneaux', count: 18 },
    ],
  },
  {
    id: 'thickness',
    title: 'Épaisseur',
    options: [
      { id: '27', label: '27 mm', count: 18 },
      { id: '34', label: '34 mm', count: 10 },
      { id: '54', label: '54 mm', count: 6 },
      { id: '80', label: '80 mm', count: 2 },
    ],
  },
  {
    id: 'quality',
    title: 'Qualité / Choix',
    options: [
      { id: 'qf1a', label: 'QF1a (Premium)', count: 8 },
      { id: 'qf2', label: 'QF2 (Standard)', count: 20 },
      { id: 'qf3', label: 'QF3 (Rustique)', count: 14 },
    ],
  },
  {
    id: 'cert',
    title: 'Certification',
    options: [
      { id: 'pefc', label: 'PEFC', count: 30 },
      { id: 'fsc', label: 'FSC', count: 12 },
    ],
  },
];
